---
- hosts: all
  roles:
    - role: common
      become: yes
      tags: [ common ]
  tasks:
    - name: create github-runner
      with_sequence: start=1 count=1
      include_role:
        name: github-runner
      vars:
        runner_name: "{{ ansible_hostname }}-{{ item }}"
        runner_work_dir: "_work"
        runner_dir: "actions-runner-{{ item }}"