---

- name: Install required packages
  yum: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
        - java-1.8.0-openjdk.x86_64
        
- name: Set JAVA_HOME
  lineinfile:
    dest: /etc/profile
    state: present
    regexp: '^JAVA_HOME='
    line: 'export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk'

- name: set JRE_HOME
  lineinfile:
    dest: /etc/profile
    state: present
    regexp: '^JRE_HOME='
    line: 'export JRE_HOME=/usr/lib/jvm/jre'
  notify: load /etc/profile
  
- name: Download Scala repo
  vars:
    scala_version: "2.13.1"
  get_url:
    url: "https://downloads.lightbend.com/scala/{{scala_version}}/scala-{{scala_version}}.rpm"
    dest: "/tmp/scala-{{scala_version}}.rpm"
  register: scala_repo

- name: Install Scala from RPM
  yum:
    name: "{{ scala_repo.dest }}"
    state: present





  


