---
- name: Set variables
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: "^={{ item.key }}"
    line: 'export {{item.key}}={{ item.value }}'
  with_items: "{{ env }}"
  notify: load /etc/environment

- name: Install common packages
  yum: 
    name: "{{ packages }}"
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python
    packages:
        - git
        - tar
        - python3-pip
        - unzip
        - yum-utils
        - device-mapper-persistent-data
        - lvm2

# - name: Add docker repository
#   yum_repository:
#     name: epel
#     description: EPEL YUM repo
#     baseurl: https://download.docker.com/linux/centos/docker-ce.repo

# - name: Install docker
#   yum:
#     name: docker-ce
#     state: latest

# - name: Assign user to docker group
#   shell: "{{ item }}"
#   with_items:
#     - usermod -aG docker $USER
#     - newgrp docker 

# - name: Start docker
#   systemd:
#     state: started
#     name: docker

- name: Install python dependencies
  pip:
    name: ['jmespath', 'pexpect']




